/**
 * init.ts — `secureclaw init` setup wizard.
 *
 * Generates cryptographically secure secrets and writes a .env file so the
 * user can start all services with `pnpm dev` without manually exporting
 * environment variables.
 *
 * Usage:
 *   secureclaw init           — interactive first-run wizard
 *   secureclaw init --force   — overwrite an existing .env
 */
import { Command } from "commander";
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import * as readline from "node:readline";

function generateHex(bytes = 32): string {
  return randomBytes(bytes).toString("hex");
}

function ask(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    let done = false;
    const finish = (v: string): void => { if (!done) { done = true; resolve(v); } };
    try {
      rl.question(question, finish);
    } catch {
      // ERR_USE_AFTER_CLOSE: stdin already closed (piped / non-interactive)
      finish("");
      return;
    }
    rl.once("close", () => finish(""));
  });
}

export function initCommand(): Command {
  return new Command("init")
    .description("Generate secrets and create a .env file for local development")
    .option("--force", "Overwrite an existing .env file without asking")
    .action(async (opts: { force?: boolean }) => {
      const envPath = join(process.cwd(), ".env");

      if (existsSync(envPath) && !opts.force) {
        process.stdout.write(
          `\n.env already exists at ${envPath}\n` +
          `  Run with --force to overwrite.\n\n`
        );
        process.exit(0);
      }

      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
      });

      process.stdout.write("\nSecureClaw Init\n");
      process.stdout.write("─────────────────────────────────────────────────\n");
      process.stdout.write("Generating cryptographically secure secrets...\n\n");

      const gatewaySecret = generateHex(32);
      const vaultKey      = generateHex(32);

      process.stdout.write(`  GATEWAY_HMAC_SECRET  ${gatewaySecret.slice(0, 8)}... (64 hex chars)\n`);
      process.stdout.write(`  VAULT_MASTER_KEY     ${vaultKey.slice(0, 8)}... (64 hex chars)\n\n`);

      // ── Interactive prompts ───────────────────────────────────────────

      const rawApiKey = await ask(
        rl,
        "Anthropic API key (sk-ant-...) — press Enter to skip for Ollama/offline:\n> "
      );

      const rawModel = await ask(
        rl,
        "\nLLM model [claude-sonnet-4-6]:\n> "
      );

      const rawOllamaUrl = await ask(
        rl,
        "\nOllama base URL — press Enter to skip [http://127.0.0.1:11434]:\n> "
      );

      rl.close();

      const apiKey    = rawApiKey.trim();
      const model     = rawModel.trim() || "claude-sonnet-4-6";
      const ollamaUrl = rawOllamaUrl.trim();

      // ── Build .env content ────────────────────────────────────────────

      const lines: string[] = [
        "# SecureClaw environment — generated by `secureclaw init`",
        "# Keep this file private. It is listed in .gitignore.",
        "",
        "# ── Gateway ────────────────────────────────────────────────────",
        `GATEWAY_HMAC_SECRET=${gatewaySecret}`,
        "",
        "# ── Credential vault (AES-256-GCM encrypted-file fallback) ─────",
        `VAULT_MASTER_KEY=${vaultKey}`,
        "",
        "# ── LLM provider ────────────────────────────────────────────────",
      ];

      if (apiKey) {
        lines.push(`ANTHROPIC_API_KEY=${apiKey}`);
      } else {
        lines.push("# ANTHROPIC_API_KEY=sk-ant-...");
      }

      lines.push(`ANTHROPIC_MODEL=${model}`);

      if (ollamaUrl) {
        lines.push(`OLLAMA_BASE_URL=${ollamaUrl}`);
      } else {
        lines.push("# OLLAMA_BASE_URL=http://127.0.0.1:11434");
      }

      lines.push(
        "",
        "# ── Optional overrides (defaults shown) ────────────────────────",
        "# GATEWAY_PORT=18789",
        "# GATEWAY_HOST=127.0.0.1",
        "# AUDIT_DATA_DIR=/tmp/secureclaw-audit",
        "# VAULT_DATA_DIR=/tmp/secureclaw-vault",
        "# MEMORY_DATA_DIR=/data/memory",
        "# SKILLS_REGISTRY_PATH=/tmp/secureclaw-skills-registry.json",
        "# MARKETPLACE_REGISTRY_PATH=/tmp/secureclaw-marketplace-registry.json",
        "# AUDIT_COST_CAP_USD=5.0",
        ""
      );

      writeFileSync(envPath, lines.join("\n"), { encoding: "utf-8", mode: 0o600 });

      process.stdout.write(`\n.env written to ${envPath}\n`);
      process.stdout.write("Permissions set to 0600 (owner-read-write only).\n\n");
      process.stdout.write("Next steps:\n");
      process.stdout.write("  pnpm build        — compile all packages (first run only)\n");
      process.stdout.write("  pnpm dev          — start all 8 services + UI\n");
      process.stdout.write("  pnpm dev:services — start backend services only (no Vite UI)\n");
      process.stdout.write("  open http://127.0.0.1:5173  — Control UI\n");
      process.stdout.write("  open http://127.0.0.1:18789 — Gateway API\n\n");
    });
}
