/**
 * schema.ts — SQLite schema for the audit system.
 *
 * CRITICAL SECURITY PROPERTY: These tables are APPEND-ONLY.
 * UPDATE and DELETE are blocked by SQLite triggers at the database level.
 * This ensures forensic integrity — no event can be erased or modified.
 */
import { DatabaseSync } from "node:sqlite";

export function initSchema(db: DatabaseSync): void {
  db.exec(`
    -- =====================================================================
    -- APPEND-ONLY audit events table
    -- Triggers below enforce this at the SQLite engine level.
    -- =====================================================================
    CREATE TABLE IF NOT EXISTS audit_events (
      id            INTEGER PRIMARY KEY AUTOINCREMENT,
      event_type    TEXT NOT NULL,
      session_id    TEXT,
      user_id       TEXT,
      payload       TEXT NOT NULL CHECK(json_valid(payload)),
      severity      TEXT NOT NULL DEFAULT 'INFO'
                    CHECK(severity IN ('INFO', 'WARN', 'ERROR', 'CRITICAL')),
      created_at    INTEGER NOT NULL
    ) STRICT;

    -- Block UPDATE on audit_events
    CREATE TRIGGER IF NOT EXISTS audit_events_no_update
      BEFORE UPDATE ON audit_events
      BEGIN
        SELECT RAISE(ABORT, 'audit_events is append-only: UPDATE not permitted');
      END;

    -- Block DELETE on audit_events
    CREATE TRIGGER IF NOT EXISTS audit_events_no_delete
      BEFORE DELETE ON audit_events
      BEGIN
        SELECT RAISE(ABORT, 'audit_events is append-only: DELETE not permitted');
      END;

    -- =====================================================================
    -- Sessions table — tracks lifetime of each agent session
    -- =====================================================================
    CREATE TABLE IF NOT EXISTS sessions (
      id              TEXT PRIMARY KEY,
      user_id         TEXT NOT NULL,
      provider        TEXT NOT NULL,
      started_at      INTEGER NOT NULL,
      ended_at        INTEGER,
      total_input_tokens  INTEGER DEFAULT 0,
      total_output_tokens INTEGER DEFAULT 0,
      total_cost_usd  REAL DEFAULT 0.0,
      tool_call_count INTEGER DEFAULT 0,
      metadata        TEXT CHECK(metadata IS NULL OR json_valid(metadata))
    ) STRICT;

    -- Sessions: allow updates (for accumulating costs), but not deletion
    CREATE TRIGGER IF NOT EXISTS sessions_no_delete
      BEFORE DELETE ON sessions
      BEGIN
        SELECT RAISE(ABORT, 'sessions is append-only: DELETE not permitted');
      END;

    -- =====================================================================
    -- Alerts — generated by the alert engine from audit events
    -- =====================================================================
    CREATE TABLE IF NOT EXISTS alerts (
      id            INTEGER PRIMARY KEY AUTOINCREMENT,
      rule_id       TEXT NOT NULL,
      severity      TEXT NOT NULL CHECK(severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
      session_id    TEXT,
      message       TEXT NOT NULL,
      context       TEXT CHECK(context IS NULL OR json_valid(context)),
      created_at    INTEGER NOT NULL,
      acknowledged  INTEGER NOT NULL DEFAULT 0 CHECK(acknowledged IN (0, 1))
    ) STRICT;

    -- Alerts: allow acknowledgment (acknowledged UPDATE), but not deletion
    CREATE TRIGGER IF NOT EXISTS alerts_no_delete
      BEFORE DELETE ON alerts
      BEGIN
        SELECT RAISE(ABORT, 'alerts is append-only: DELETE not permitted');
      END;

    -- =====================================================================
    -- Cost ledger — per-call token usage and cost tracking
    -- =====================================================================
    CREATE TABLE IF NOT EXISTS cost_ledger (
      id            INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id    TEXT NOT NULL,
      user_id       TEXT NOT NULL,
      provider      TEXT NOT NULL,
      model         TEXT NOT NULL,
      input_tokens  INTEGER NOT NULL DEFAULT 0,
      output_tokens INTEGER NOT NULL DEFAULT 0,
      cost_usd      REAL NOT NULL DEFAULT 0.0,
      recorded_at   INTEGER NOT NULL
    ) STRICT;

    CREATE TRIGGER IF NOT EXISTS cost_ledger_no_update
      BEFORE UPDATE ON cost_ledger
      BEGIN
        SELECT RAISE(ABORT, 'cost_ledger is append-only: UPDATE not permitted');
      END;

    CREATE TRIGGER IF NOT EXISTS cost_ledger_no_delete
      BEFORE DELETE ON cost_ledger
      BEGIN
        SELECT RAISE(ABORT, 'cost_ledger is append-only: DELETE not permitted');
      END;

    -- =====================================================================
    -- Indexes for query performance
    -- =====================================================================
    CREATE INDEX IF NOT EXISTS idx_events_session   ON audit_events(session_id);
    CREATE INDEX IF NOT EXISTS idx_events_type      ON audit_events(event_type);
    CREATE INDEX IF NOT EXISTS idx_events_created   ON audit_events(created_at);
    CREATE INDEX IF NOT EXISTS idx_events_severity  ON audit_events(severity);
    CREATE INDEX IF NOT EXISTS idx_cost_user_day    ON cost_ledger(user_id, recorded_at);
    CREATE INDEX IF NOT EXISTS idx_alerts_session   ON alerts(session_id);
    CREATE INDEX IF NOT EXISTS idx_alerts_ack       ON alerts(acknowledged);
  `);

  // Migration: add team_id column (idempotent — SQLite ALTER ADD COLUMN is safe to retry)
  try {
    db.exec("ALTER TABLE cost_ledger ADD COLUMN team_id TEXT NOT NULL DEFAULT ''");
  } catch { /* column already exists — safe to ignore */ }
  try {
    db.exec("CREATE INDEX IF NOT EXISTS idx_cost_team_day ON cost_ledger(team_id, recorded_at)");
  } catch { /* index already exists */ }
}
